//! Our decoders against somebody else's.
//!
//! The block decoders in this crate are written to be read against
//! `ggml-quants.c`. That catches a layout misremembered; it does not catch one
//! misread the same way twice, because the only other thing agreeing with them
//! is them.
//!
//! So `tests/golden/` holds vectors produced by `gguf-py` -- the llama.cpp
//! project's own GGUF library, written in numpy, by other people, from the same
//! specification. Half are blocks it quantized itself; half are lifted out of
//! real checkpoints, which is the only way to reach the K-quants since gguf-py
//! decodes those without being able to produce them.
//!
//! Decoding a block is integer arithmetic and one or two half-precision scales.
//! Nothing in it can round two ways, so this asserts *equality*: one differing
//! bit is a wrong decoder, not a tolerance to widen. `scripts/golden-vectors.py`
//! regenerates them and records where each came from.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use gguf_quants::{dequantize, GgmlType};

/// The dtype whose own `name()` is this one. There is no name lookup in the
/// crate -- the tag is how a file names a format -- so this walks the tags and
/// asks each what it is called, which is also a check that `name()` round-trips.
fn dtype_by_name(name: &str) -> Result<GgmlType, String> {
    (0u32..40)
        .filter_map(|tag| GgmlType::from_u32(tag).ok())
        .find(|dtype| dtype.name() == name)
        .ok_or_else(|| format!("no dtype named {name}"))
}

fn golden_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/golden")
}

fn read_f32(path: &Path) -> Vec<f32> {
    let bytes = std::fs::read(path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    assert_eq!(bytes.len() % 4, 0, "{} is not whole f32s", path.display());
    bytes
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect()
}

/// Which formats the vectors cover, and what each one's source was.
fn manifest() -> BTreeMap<String, String> {
    let text = std::fs::read_to_string(golden_dir().join("manifest.json"))
        .expect("tests/golden/manifest.json (run scripts/golden-vectors.py)");
    // A three-line parse rather than a serde dependency for one test file: the
    // manifest is generated by a script in this repository, not by a stranger.
    let mut out = BTreeMap::new();
    let mut name: Option<String> = None;
    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed.ends_with("\": {") {
            name = Some(
                trimmed
                    .trim_start_matches('"')
                    .trim_end_matches("\": {")
                    .into(),
            );
        } else if let (Some(key), Some(rest)) =
            (name.as_ref(), trimmed.strip_prefix("\"from\": \""))
        {
            out.insert(
                key.clone(),
                rest.trim_end_matches("\",").trim_end_matches('"').into(),
            );
        }
    }
    out
}

#[test]
fn every_decoder_agrees_with_gguf_py() {
    let vectors = manifest();
    assert!(!vectors.is_empty(), "no golden vectors found");

    for (name, provenance) in &vectors {
        let dtype = dtype_by_name(name).unwrap_or_else(|e| panic!("{e}"));
        let blocks = std::fs::read(golden_dir().join(format!("{name}.blocks")))
            .unwrap_or_else(|e| panic!("{name}.blocks: {e}"));
        let expected = read_f32(&golden_dir().join(format!("{name}.f32")));

        let mut ours = vec![0.0f32; expected.len()];
        dequantize(dtype, &blocks, &mut ours).unwrap_or_else(|e| panic!("{name}: {e}"));

        // Compared by bits, so a -0.0 that should be 0.0 is caught and a NaN
        // does not quietly compare unequal to itself and pass as "differs".
        for (i, (got, want)) in ours.iter().zip(&expected).enumerate() {
            assert_eq!(
                got.to_bits(),
                want.to_bits(),
                "{name} value {i}: {got} is not {want} (vectors from {provenance})"
            );
        }
        assert_eq!(ours.len(), expected.len(), "{name} length");
    }
}

/// Every format this crate decodes has an independent vector.
///
/// The blocks are synthesised rather than taken from a checkpoint, which is
/// what makes this reachable: gguf-py decodes the K-quants without being able
/// to produce them, but a decoder does not need a quantizer. Every bit pattern
/// is a legal block, so pseudo-random bytes with finite f16 scales are a valid
/// block of any format -- and better coverage than real weights, which cluster
/// where an off-by-one in a shift does not show.
#[test]
fn no_format_is_left_without_a_vector() {
    let covered = manifest();
    let all = [
        "F32", "F16", "BF16", "Q4_0", "Q4_1", "Q5_0", "Q5_1", "Q8_0", "Q2_K", "Q3_K", "Q4_K",
        "Q5_K", "Q6_K", "IQ4_NL", "IQ4_XS",
    ];
    let missing: Vec<_> = all.iter().filter(|n| !covered.contains_key(**n)).collect();
    assert!(
        missing.is_empty(),
        "these decoders have nothing independent checking them: {missing:?}"
    );
    for name in covered.keys() {
        assert!(
            all.contains(&name.as_str()),
            "{name} has a vector but is not a format this crate decodes"
        );
        assert!(
            dtype_by_name(name).is_ok(),
            "{name} is not a dtype this crate has"
        );
    }
}
